apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgZ3JvdXBfYnk6IFsnYWxlcnRuYW1lJywgJ2NsdXN0ZXInLCAnc2VydmljZScsICdqb2InXQogIGdyb3VwX3dhaXQ6IDMwcwogIGdyb3VwX2ludGVydmFsOiA1bQogIHJlcGVhdF9pbnRlcnZhbDogMWgKICByZWNlaXZlcjogZGVmYXVsdC1yZWNlaXZlcgogIHJvdXRlczoKICAtIG1hdGNoOgogICAgICBzZXZlcml0eTogY3JpdGljYWx8d2FybmluZwogICAgcmVjZWl2ZXI6IGRlZmF1bHQtcmVjZWl2ZXIKICAtIG1hdGNoOiAKICAgICAgYWxlcnRuYW1lOiBXYXRjaGRvZwogICAgcmVjZWl2ZXI6IGRlZmF1bHQtcmVjZWl2ZXIKcmVjZWl2ZXJzOgotIG5hbWU6IGRlZmF1bHQtcmVjZWl2ZXIKICB3ZWJob29rX2NvbmZpZ3M6CiAgICAtIHNlbmRfcmVzb2x2ZWQ6IHRydWUKICAgICAgdXJsOiBodHRwOi8vYWxlcnRtYW5hZ2VyLWJvdDo4MDgw
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
